// <auto-generated />
namespace Web_Project_Tour_and_Travel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addmigratin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigratin));
        
        string IMigrationMetadata.Id
        {
            get { return "202405051312448_add-migratin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
